service: flow-report

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role: arn:aws:iam::303732912389:role/lambda-role

functions:
  flowReport:
    handler: handler.flowReport

plugins:
  - serverless-offline
